In [1]:
# What is numpy?

In [2]:
# Numerical Python
# Numpy is a python library used for working with arrays, mathematical operations and machine learning.

In [3]:
# Why we need numpy?

In [4]:
numbers = [10, 20, 30, 40]
results = []

for i in numbers:
    results.append(i+1)

print(results)

[11, 21, 31, 41]


In [5]:
import numpy as np

In [6]:
arr = np.array([10, 20, 30, 40])

print(arr + 1)

[11 21 31 41]


In [7]:
# What is array?

In [8]:
# An array is a collection of elements stored together

In [9]:
# How to create 1D array?

In [10]:
arr = np.array([10, 20, 30, 40, 78, 22])

print(arr)

[10 20 30 40 78 22]


In [11]:
# How to create 2D array?

In [12]:
students = np.array([[85, 90], [79, 92], [89, 99]])

print(students)

[[85 90]
 [79 92]
 [89 99]]


In [13]:
# How to create 3D array?

In [14]:
data = np.array([[[85, 90], [78, 92]], [[79, 99], [73, 91]]])

print(data)

[[[85 90]
  [78 92]]

 [[79 99]
  [73 91]]]


In [15]:
# Array Atributes

In [16]:
# how many rows are there?
# how many columns are there?
# what datatype is used?
# how much memory is consumed?

In [17]:
# ndim

In [18]:
print(arr.ndim)
print(students.ndim)
print(data.ndim)

1
2
3


In [19]:
# shape

In [20]:
print(students.shape)

(3, 2)


In [21]:
# size

In [22]:
print(students.size)

6


In [23]:
# dtype

In [24]:
print(students.dtype)

int64


In [25]:
# itemsize

In [26]:
print(students.itemsize)

8


In [27]:
# special arrays

In [28]:
# np.zeros()

In [29]:
# 1D array
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [30]:
arr2 = np.zeros((3, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
# np.ones()

In [32]:
arr3 = np.ones((3, 4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# np.empty()

In [34]:
arr4 = np.empty((3, 4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
# np.full()

In [36]:
arr5 = np.full((3, 4), 22)
print(arr5)

[[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]


In [37]:
# np.eye()

In [38]:
arr5 = np.eye(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# np.identity()

In [40]:
arr6 = np.identity(5)
print(arr6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# sequence arrays

In [42]:
# np.arange()

In [43]:
# syntax
# np.arange(start, stop, step)

In [44]:
arr22 = np.arange(5)
print(arr22)

[0 1 2 3 4]


In [45]:
# np.linspace()

In [46]:
# syntax
# np.linspace(start, stop, num)

In [47]:
arr23 = np.linspace(1, 10, 5)
print(arr23)

[ 1.    3.25  5.5   7.75 10.  ]


In [48]:
# array conversions

In [49]:
# from list to array

In [50]:
marks = [99, 78, 89, 80]
print(marks)

arr45 = np.array(marks)
print(arr45)

[99, 78, 89, 80]
[99 78 89 80]


In [51]:
# indexing

In [52]:
# 1d
marks = np.array([85, 90, 78, 92])

In [53]:
print(marks[0])

85


In [54]:
print(marks[-2])

78


In [56]:
# 2d
students = np.array([[85, 90], [78, 92], [88, 95]])

In [58]:
print(students[1, 0])

78


In [59]:
# 3d
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [60]:
print(arr[1,0,1])

6


In [61]:
# slicing

In [62]:
marks = np.array([85, 90, 78, 92])

In [64]:
print(marks[0:3])

[85 90 78]


In [65]:
# numpy mathematical operations

In [66]:
marks1 = np.array([85, 90, 78, 92])

In [67]:
print(marks1+5)

[90 95 83 97]


In [68]:
marks2 = np.array([85, 90, 78, 92])

In [69]:
print(marks1-5)

[80 85 73 87]


In [71]:
marks2 = np.array([5, 9, 8, 2])

In [72]:
print(marks2 ** 2)

[25 81 64  4]


In [73]:
# statistical functions in numpy

In [77]:
x = np.array([5, 9, 3, 8, 2])

In [78]:
print(np.sum(x))

27


In [79]:
print(np.mean(x))

5.4


In [80]:
print(np.median(x))

5.0


In [81]:
print(np.min(x))
print(np.max(x))

2
9


In [82]:
print(np.std(x))

2.727636339397171


In [83]:
print(np.var(x))

7.44


In [84]:
# reshape()

In [86]:
x = np.array([5, 9, 3, 8, 2, 1])

In [87]:
x.reshape(2, 3)

array([[5, 9, 3],
       [8, 2, 1]])

In [88]:
# SORT()

In [89]:
y = np.array([5, 9, 3, 8, 2, 1])

In [90]:
print(np.sort(y))

[1 2 3 5 8 9]


In [91]:
print(np.sort(y)[::-1])

[9 8 5 3 2 1]


In [92]:
# where()

In [93]:
z = np.array([5, 9, 3, 8, 2, 1])

In [95]:
print(np.where(z==9))

(array([1]),)


In [96]:
# argmax() & argmin()

In [ ]:
print(np.argmax(z))
print(np)