In [1]:
# What is numpy?

In [2]:
# Numerical Python
# Numpy is a python library used for working with arrays, mathematical operations and machine learning.

In [3]:
# Why we need numpy?

In [4]:
numbers = [10, 20, 30, 40]
results = []

for i in numbers:
    results.append(i+1)

print(results)

[11, 21, 31, 41]


In [7]:
import numpy as np

In [8]:
arr = np.array([10, 20, 30, 40])

print(arr + 1)

[11 21 31 41]


In [9]:
# What is array?

In [10]:
# An array is a collection of elements stored together

In [11]:
# How to create 1D array?

In [13]:
arr = np.array([10, 20, 30, 40, 78, 22])

print(arr)

[10 20 30 40 78 22]


In [14]:
# How to create 2D array?

In [15]:
students = np.array([[85, 90], [79, 92], [89, 99]])

print(students)

[[85 90]
 [79 92]
 [89 99]]


In [16]:
# How to create 3D array?

In [17]:
data = np.array([[[85, 90], [78, 92]], [[79, 99], [73, 91]]])

print(data)

[[[85 90]
  [78 92]]

 [[79 99]
  [73 91]]]


In [18]:
# Array Atributes

In [20]:
# how many rows are there?
# how many columns are there?
# what datatype is used?
# how much memory is consumed?

In [21]:
# ndim

In [22]:
print(arr.ndim)
print(students.ndim)
print(data.ndim)

1
2
3


In [23]:
# shape

In [24]:
print(students.shape)

(3, 2)


In [25]:
# size

In [26]:
print(students.size)

6


In [27]:
# dtype

In [28]:
print(students.dtype)

int64


In [29]:
# itemsize

In [30]:
print(students.itemsize)

8


In [31]:
# special arrays

In [32]:
# np.zeros()

In [33]:
# 1D array
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [34]:
arr2 = np.zeros((3, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
# np.ones()

In [36]:
arr3 = np.ones((3, 4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
# np.empty()

In [39]:
arr4 = np.empty((3, 4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
# np.full()

In [42]:
arr5 = np.full((3, 4), 22)
print(arr5)

[[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]


In [43]:
# np.eye()

In [44]:
arr5 = np.eye(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
# np.identity()

In [46]:
arr6 = np.identity(5)
print(arr6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
# sequence arrays

In [48]:
# np.arange()

In [50]:
# syntax
# np.arange(start, stop, step)

In [51]:
arr22 = np.arange(5)
print(arr22)

[0 1 2 3 4]


In [52]:
# np.linspace()

In [53]:
# syntax
# np.linspace(start, stop, num)

In [54]:
arr23 = np.linspace(1, 10, 5)
print(arr23)

[ 1.    3.25  5.5   7.75 10.  ]


In [55]:
# array conversions

In [56]:
# from list to array

In [58]:
marks = [99, 78, 89, 80]
print(marks)

arr45 = np.array(marks)
print(arr45)

[99, 78, 89, 80]
[99 78 89 80]
